version: '3'

services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
    container_name: cafe-shares-db
  api:
    tty: true         #コンテナ上でbinding.pryするために必要
    stdin_open: true  #コンテナ上でbinding.pryするために必要
    build:
      context: ./backend-api/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend-api:/cafe-shares-api  #ローカルのディレクトリをコンテナ上にマウント
    links:
      - db
    depends_on:
      - db
    container_name: cafe-shares-api
  client:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    command: "yarn dev"
    ports:
      - "8000:3000"
    container_name: cafe-shares-client
volumes:
  mysql-db: