version: '3'

services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: cafe-shares-db
  web:
    tty: true         #コンテナ上でbinding.pryするために必要
    stdin_open: true  #コンテナ上でbinding.pryするために必要
    build: .
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/cafe-shares  #ローカルのディレクトリをコンテナ上にマウント
      - bundle:/usr/local/bundle  #bundle installした後にbuildし直さなくてよくなる
    links:
      - db
    depends_on:
      - db
    container_name: cafe-shares-web
volumes:
  bundle:  #bundle installした後にbuildし直さなくてよくなる
  mysql_data: