version: '3'

services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
    container_name: cafe-shares-db
  api:
    tty: true         #コンテナ上でbinding.pryするために必要
    stdin_open: true  #コンテナ上でbinding.pryするために必要
    build: .
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/cafe-shares-api  #ローカルのディレクトリをコンテナ上にマウント
    links:
      - db
    depends_on:
      - db
    container_name: cafe-shares-api
volumes:
  mysql-db: